# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default='rock', max_length=160),
            preserve_default=False,
        ),
    ]
