# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170806_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='composer_name',
            field=models.CharField(blank=True, default=None, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='music.Composer'),
        ),
    ]
