# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170806_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.ManyToManyField(to='music.Composer'),
        ),
    ]
