# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170806_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='byte',
        ),
        migrations.AddField(
            model_name='track',
            name='byte_s',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
