# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170806_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='byte_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='milliseconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
