# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='billing_tate',
            new_name='billing_date',
        ),
    ]
