# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170806_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='billing_City',
            new_name='billing_city',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='billing_Country',
            new_name='billing_country',
        ),
    ]
