# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170806_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billing_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.CharField(max_length=40),
        ),
    ]
