# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170806_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(),
        ),
    ]
