# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170806_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_state',
            new_name='billing_state',
        ),
    ]
