# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20170806_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_postal_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_state',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
