# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170806_2048'),
        ('customer', '0007_auto_20170806_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_list', models.CharField(max_length=60)),
                ('customer', models.ManyToManyField(to='customer.Customer')),
            ],
            options={
                'ordering': ('play_list',),
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Track')),
            ],
        ),
    ]
