# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170806_2048'),
        ('customer', '0009_auto_20170806_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttrack',
            name='play_list',
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='track',
        ),
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(to='music.Track'),
        ),
        migrations.DeleteModel(
            name='PlaylistTrack',
        ),
    ]
