# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('reports_to', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('birth_date', models.DateTimeField()),
                ('hire_date', models.DateTimeField()),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=24)),
                ('fax', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
    ]
