# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20170806_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reports_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
